-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 14:17:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_company` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurant_company` ;

-- -----------------------------------------------------
-- Table `restaurant_company`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`address` (
  `Address_id` INT NOT NULL,
  `City` VARCHAR(25) NOT NULL,
  `Town` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`restaurant` (
  `Restaurant_id` INT NOT NULL,
  PRIMARY KEY (`Restaurant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`transfer` (
  `Transfer_id` INT NOT NULL,
  `Transfer_date` DATE NOT NULL,
  `Delivererd` DATE NOT NULL,
  PRIMARY KEY (`Transfer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`dishes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`dishes` (
  `Serial_number` INT NOT NULL,
  `Name` VARCHAR(25) NOT NULL,
  `Description` VARCHAR(25) NOT NULL,
  `Purchase_price` INT NOT NULL,
  `Prepared_date` DATE NOT NULL,
  `Served_dat` DATE NOT NULL,
  `restaurant_Restaurant_id` INT NOT NULL,
  `transfer_Transfer_id` INT NOT NULL,
  PRIMARY KEY (`Serial_number`),
  INDEX `fk_dishes_restaurant1_idx` (`restaurant_Restaurant_id` ASC) VISIBLE,
  INDEX `fk_dishes_transfer1_idx` (`transfer_Transfer_id` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_restaurant1`
    FOREIGN KEY (`restaurant_Restaurant_id`)
    REFERENCES `restaurant_company`.`restaurant` (`Restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_transfer1`
    FOREIGN KEY (`transfer_Transfer_id`)
    REFERENCES `restaurant_company`.`transfer` (`Transfer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`categorys` (
  `Category_id` INT NOT NULL,
  `Starter` VARCHAR(25) NOT NULL,
  `Mail_course` VARCHAR(25) NOT NULL,
  `Dessert` INT NOT NULL,
  `dishes_Serial_number` INT NOT NULL,
  PRIMARY KEY (`Category_id`),
  INDEX `fk_categorys_dishes1_idx` (`dishes_Serial_number` ASC) VISIBLE,
  CONSTRAINT `fk_categorys_dishes1`
    FOREIGN KEY (`dishes_Serial_number`)
    REFERENCES `restaurant_company`.`dishes` (`Serial_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`customers` (
  `Customer_id` INT NOT NULL,
  `Firstname` VARCHAR(25) NOT NULL,
  `Lastname` VARCHAR(25) NOT NULL,
  `restaurant_Restaurant_id` INT NOT NULL,
  `address_Address_id` INT NOT NULL,
  PRIMARY KEY (`Customer_id`, `address_Address_id`),
  INDEX `fk_customers_restaurant1_idx` (`restaurant_Restaurant_id` ASC) VISIBLE,
  INDEX `fk_customers_address1_idx` (`address_Address_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_restaurant1`
    FOREIGN KEY (`restaurant_Restaurant_id`)
    REFERENCES `restaurant_company`.`restaurant` (`Restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_address1`
    FOREIGN KEY (`address_Address_id`)
    REFERENCES `restaurant_company`.`address` (`Address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`waiters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`waiters` (
  `Waiter_id` INT NOT NULL,
  `Surname` VARCHAR(25) NOT NULL,
  `Firstname` VARCHAR(25) NOT NULL,
  `Fixed_salary` INT NOT NULL,
  `restaurant_Restaurant_id` INT NOT NULL,
  `address_Address_id` INT NOT NULL,
  PRIMARY KEY (`Waiter_id`, `restaurant_Restaurant_id`, `address_Address_id`),
  INDEX `fk_waiters_restaurant1_idx` (`restaurant_Restaurant_id` ASC) VISIBLE,
  INDEX `fk_waiters_address1_idx` (`address_Address_id` ASC) VISIBLE,
  CONSTRAINT `fk_waiters_restaurant1`
    FOREIGN KEY (`restaurant_Restaurant_id`)
    REFERENCES `restaurant_company`.`restaurant` (`Restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_waiters_address1`
    FOREIGN KEY (`address_Address_id`)
    REFERENCES `restaurant_company`.`address` (`Address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`orders` (
  `Order_id` INT NOT NULL,
  `Customer` VARCHAR(25) NOT NULL,
  `Waiter` VARCHAR(25) NOT NULL,
  `Dishes` VARCHAR(25) NOT NULL,
  `customers_Customer_id` INT NOT NULL,
  `waiters_Waiter_id` INT NOT NULL,
  `dishes_Serial_number` INT NOT NULL,
  PRIMARY KEY (`Order_id`),
  INDEX `fk_orders_customers1_idx` (`customers_Customer_id` ASC) VISIBLE,
  INDEX `fk_orders_waiters1_idx` (`waiters_Waiter_id` ASC) VISIBLE,
  INDEX `fk_orders_dishes1_idx` (`dishes_Serial_number` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customers_Customer_id`)
    REFERENCES `restaurant_company`.`customers` (`Customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_waiters1`
    FOREIGN KEY (`waiters_Waiter_id`)
    REFERENCES `restaurant_company`.`waiters` (`Waiter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_dishes1`
    FOREIGN KEY (`dishes_Serial_number`)
    REFERENCES `restaurant_company`.`dishes` (`Serial_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_company`.`dishes_has_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_company`.`dishes_has_restaurant` (
  `dishes_Serial_number` INT NOT NULL,
  `restaurant_Restaurant_id` INT NOT NULL,
  PRIMARY KEY (`dishes_Serial_number`, `restaurant_Restaurant_id`),
  INDEX `fk_dishes_has_restaurant_restaurant1_idx` (`restaurant_Restaurant_id` ASC) VISIBLE,
  INDEX `fk_dishes_has_restaurant_dishes_idx` (`dishes_Serial_number` ASC) VISIBLE,
  CONSTRAINT `fk_dishes_has_restaurant_dishes`
    FOREIGN KEY (`dishes_Serial_number`)
    REFERENCES `restaurant_company`.`dishes` (`Serial_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dishes_has_restaurant_restaurant1`
    FOREIGN KEY (`restaurant_Restaurant_id`)
    REFERENCES `restaurant_company`.`restaurant` (`Restaurant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
